name: tootles

services:
  # This service assumes you are only using one machine for development or using wired control
  tootles_wired:
    extends:
      file: compose-base.yaml
      service: tootles_base

    container_name: tootles_base

    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

    profiles:
      - wired
